# syntax=docker/dockerfile:1.4
ARG VERSION=2.11.3

FROM caddy:${VERSION}-builder AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/inwx \
    --with github.com/hslatman/caddy-crowdsec-bouncer/crowdsec

FROM cgr.dev/chainguard/wolfi-base

ARG CADDY_IMAGE_VERSION
ARG BUILD_DATE
ARG GITHUB_SHA
ARG CADDY_CROWDSEC_BOUNCER_VERSION
ARG CADDY_DNS_INWX_VERSION

LABEL org.opencontainers.image.title="caddy"
LABEL org.opencontainers.image.description="Personal Caddy Container Image with INWX and Crowdsec modules included."
LABEL org.opencontainers.image.url="ghcr.io/markaltmann/caddy-image/caddy:latest"
LABEL org.opencontainers.image.source="https://github.com/markaltmann/caddy-image"
LABEL org.opencontainers.image.version="${CADDY_IMAGE_VERSION}"
LABEL org.opencontainers.image.created="${BUILD_DATE}"
LABEL org.opencontainers.image.revision="${GITHUB_SHA}"
LABEL org.opencontainers.image.licenses="The Unlicense"
LABEL org.opencontainers.image.authors="Mark Altmann <mark@altmann.it>"
LABEL org.opencontainers.image.component.caddy-crowdsec-bouncer="${CADDY_CROWDSEC_BOUNCER_VERSION}"
LABEL org.opencontainers.image.component.caddy-dns-inwx="${CADDY_DNS_INWX_VERSION}"
LABEL org.opencontainers.image.component.caddy-image="${CADDY_IMAGE_VERSION}"

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

# Install libcap to apply capabilities and then remove it to keep the image minimal
# Wolfi base image uses apk.
RUN apk add --no-cache libcap && \
    setcap cap_net_bind_service=+ep /usr/bin/caddy && \
    apk del libcap

EXPOSE 80 443

USER 65532:65532

ENTRYPOINT ["/usr/bin/caddy"]
CMD ["run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
