name: Build Multi-Arch Caddy Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - refs.txt
  pull_request:
    branches:
      - main
    paths:
      - refs.txt

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

      - name: Parse refs.txt for component versions
        id: refs
        run: |
          while IFS== read -r key value; do
            echo "$key=$value" >> $GITHUB_ENV
            if [ "$key" = "caddy-image" ]; then
              echo "caddy-version-no-v=${value#v}" >> $GITHUB_ENV
            fi
          done < refs.txt

      - name: Build and push multi-arch image with Buildah
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.13
        with:
          image: ghcr.io/${{ github.repository }}/caddy
          tags: latest
          containerfiles: ./Caddy/Dockerfile.caddy
          platforms: linux/amd64,linux/arm64
          oci: true
          push: true
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          build-args: |
            VERSION=${{ env.caddy-version-no-v }}
            CADDY_IMAGE_VERSION=${{ env.caddy-image }}
            BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            GITHUB_SHA=${{ github.sha }}
            CADDY_CROWDSEC_BOUNCER_VERSION=${{ env.caddy-crowdsec-bouncer }}
            CADDY_DNS_INWX_VERSION=${{ env.caddy-dns-inwx }}
